//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oaiharvester
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SubjectSmallMetadata_02Context : DbContext
    {
        public SubjectSmallMetadata_02Context()
            : base("name=SubjectSmallMetadata_02Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_SubjectSmallMeDa_02> T_SubjectSmallMeDa_02 { get; set; }
    }
}
